Repository theforeman/foreman-tasks, pull requests merged in 2018-09, with the labels that each got.

#356 Add 0.14.0 to the matrix
  README.md
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#357 Fixes #24830 - Improve search by user
  app/models/foreman_tasks/task.rb
  test/unit/task_test.rb
Labels: Needs testing, Not yet reviewed

#359 Fixes #24648 - handle safe params in import_facts
  app/lib/actions/foreman/host/import_facts.rb
Labels: Needs testing

#358 Fixes #24872 - fix import_facts deprecation
  app/lib/actions/foreman/host/import_facts.rb
Labels: Needs testing

#361 Fixes #24909 - Mark proxy tasks as failed only if confirmed
  app/lib/actions/middleware/watch_delegated_proxy_sub_tasks.rb
Labels: Needs testing, Not yet reviewed
