Repository theforeman/foreman-tasks, pull requests merged in 2018-03, with the labels that each got.

#317 Fixes #22838 - avoid double-initialization of Dynflow runtime
  lib/foreman_tasks/engine.rb
Labels: Needs testing

#318 Fixes #22864 - Extract the latest strings from the dev branch
  locale/action_names.rb
  locale/en/foreman_tasks.po
  locale/foreman_tasks.pot
Labels: Needs testing, Not yet reviewed

#322 Fixes #22920 - Access variable, not datastructure
  app/lib/actions/foreman/host/import_facts.rb
Labels: Needs testing, Not yet reviewed

#320 Fixes #22915 - Make the cleaner clean orphaned dynflow plans
  lib/foreman_tasks/cleaner.rb
  test/unit/cleaner_test.rb
Labels: Needs testing, Not yet reviewed

#327 Fixes #22999 - repo synchronization task page have broken link
  app/lib/actions/helpers/humanizer.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#325 Refs #22969: Add keep_current_* midware tests
  app/lib/actions/middleware/keep_current_taxonomies.rb
  test/lib/actions/middleware/keep_current_taxonomies_test.rb
  test/lib/actions/middleware/keep_current_user_test.rb
Labels: Needs testing, Not yet reviewed

#328 Refs #22969: s/taxonomies/user/ in midware test
  test/lib/actions/middleware/keep_current_user_test.rb
Labels: Needs testing, Not yet reviewed

#311 Fixes #21802 - Make recurring tasks more resilient
  app/helpers/foreman_tasks/foreman_tasks_helper.rb
  app/lib/actions/middleware/recurring_logic.rb
  app/lib/actions/recurring_action.rb
  app/models/foreman_tasks/recurring_logic.rb
  app/models/foreman_tasks/task/dynflow_task.rb
  foreman-tasks.gemspec
  lib/foreman_tasks/engine.rb
  test/unit/actions/recurring_action_test.rb
  test/unit/recurring_logic_test.rb
  test/unit/task_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on Dependencies

#319 Fixes #22887 - update persistence initialization code
  foreman-tasks.gemspec
  lib/foreman_tasks/dynflow/configuration.rb
Labels: Needs testing, Waiting on Dependencies, Waiting on contributor
