Repository theforeman/foreman-tasks, pull requests merged in 2018-04, with the labels that each got.

#329 Refs #22849 - update .rubocop_todo.yml
  .rubocop_todo.yml
Labels: Ready to merge

#238 Fixes #18758 - Allow ActiveJobs to be displayed in the tasks lists
  app/models/foreman_tasks/task.rb
  app/models/foreman_tasks/task/dynflow_task.rb
Labels: Ready to merge

#333 Fixes #23355 - Replace alias_method_chain with prepend
  app/controllers/foreman_tasks/concerns/hosts_controller_extension.rb
  lib/foreman_tasks/engine.rb
Labels: Needs testing, Not yet reviewed

#332 Fixes #23348 - Set label field properly
  app/models/foreman_tasks/task/dynflow_task.rb
Labels: Needs testing
