Repository theforeman/foreman-tasks, pull requests merged in 2018-06, with the labels that each got.

#341 Fixes #23814 - ensure to clean locks on tasks cleanup
  lib/foreman_tasks/cleaner.rb
  test/unit/cleaner_test.rb
Labels: Needs testing

#343 Fixes #23821 - Drop support for Rails 4
  app/lib/actions/base.rb
  app/models/foreman_tasks/recurring_logic.rb
  app/models/foreman_tasks/task.rb
  lib/foreman_tasks.rb
Labels: Needs testing

#344 Fixes #23585 - allow future start date for recurring tasks
  app/models/foreman_tasks/recurring_logic.rb
  test/foreman_tasks_test_helper.rb
  test/support/dummy_recurring_dynflow_action.rb
  test/unit/recurring_logic_test.rb
Labels: Needs testing

#330 Fixes #23244 - Migrate two-pane to breadcrumb-bar
  app/controllers/foreman_tasks/api/tasks_controller.rb
  app/views/foreman_tasks/api/tasks/show.json.rabl
  app/views/foreman_tasks/tasks/index.html.erb
  app/views/foreman_tasks/tasks/show.html.erb
Labels: Needs testing

#345 Fixes #23849 - Restore current user+taxonomies when running hooks
  app/lib/actions/middleware/keep_current_taxonomies.rb
  app/lib/actions/middleware/keep_current_user.rb
  foreman-tasks.gemspec
Labels: Needs testing, Not yet reviewed

#346 Fixes #23881 - Document pagination of recurring logic in apidoc
  app/controllers/foreman_tasks/api/recurring_logics_controller.rb
Labels: Needs testing, Not yet reviewed

#349 Refs #23837: incl `update` in actn_trggr methods
  app/models/foreman_tasks/concerns/action_triggering.rb
Labels: Needs re-review, Needs testing
