Repository theforeman/foreman-tasks, pull requests merged in 2018-05, with the labels that each got.

#298 Fixes #23017 - Rex resilience
  app/lib/actions/helpers/with_continuous_output.rb
  app/lib/actions/middleware/watch_delegated_proxy_sub_tasks.rb
  app/lib/actions/proxy_action.rb
  app/lib/proxy_api/foreman_dynflow/dynflow_proxy.rb
  app/models/foreman_tasks/remote_task.rb
  app/models/foreman_tasks/task.rb
  app/models/setting/foreman_tasks.rb
  db/migrate/20180207150921_add_remote_tasks.foreman_tasks.rb
  lib/foreman_tasks/cleaner.rb
  test/unit/actions/proxy_action_test.rb
Labels: Needs re-review, Needs testing

#336 Fix dynflow-executor task in README
  README.md
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#337 Package name change?
  README.md
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#334 Fixes #23504 - Port robottelo tests for foreman_task
  test/controllers/api/tasks_controller_test.rb
Labels: Needs testing, Not yet reviewed

#338 readme: add compatibility chart
  README.md
Labels: Needs testing, Not yet reviewed, Waiting on contributor
