Repository theforeman/foreman-tasks, pull requests merged in 2019-11, with the labels that each got.

#446 Refs #26346 - tasks table uses router history
  webpack/ForemanTasks/Components/TasksDashboard/TasksDashboard.js
  webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardActions.js
  webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardHelper.js
  webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardSelectors.js
  webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboard.test.js
  webpack/ForemanTasks/Components/TasksTable/TasksTable.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableHelpers.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableReducer.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableHelpers.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTable.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableReducer.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/index.js
  webpack/ForemanTasks/Routes/ForemanTasksRouter.test.js
  webpack/ForemanTasks/Routes/ForemanTasksRoutes.test.js
  webpack/ForemanTasks/Routes/ShowTask/__tests__/ShowTask.test.js
  webpack/ForemanTasks/Routes/__snapshots__/ForemanTasksRoutes.test.js.snap
Labels: Needs testing

#459 Fixes #27815 - setting initialization improvement
  app/models/setting/foreman_tasks.rb
Labels: Needs testing

#461 Fixes #27801 - Add cancel button to the tasks table
  app/controllers/foreman_tasks/tasks_controller.rb
  app/views/foreman_tasks/api/tasks/show.json.rabl
  webpack/ForemanTasks/Components/TaskDetails/Components/Task.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsActions.js
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/TaskTableFormmatters.js
  webpack/ForemanTasks/Components/TasksTable/TasksTable.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableActions.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
  webpack/ForemanTasks/Components/common/Cancel/Cancel.js
  webpack/ForemanTasks/Components/common/Cancel/Cancel.test.js
  webpack/ForemanTasks/Components/common/Cancel/__snapshots__/Cancel.test.js.snap
  webpack/__mocks__/foremanReact/redux/actions/toasts.js
Labels: Needs testing

#470 Fixes #28152 - Link tasks with user only if the user exists
  db/migrate/20180927120509_add_user_id.foreman_tasks.rb
Labels: Ready to merge

#462 Fixes #27802 - Add resume button to the tasks table
  app/controllers/foreman_tasks/tasks_controller.rb
  app/views/foreman_tasks/api/tasks/show.json.rabl
  webpack/ForemanTasks/Components/TaskDetails/Components/Task.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsActions.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/TaskTableFormmatters.js
  webpack/ForemanTasks/Components/TasksTable/TasksTable.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableActions.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
  webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.js
  webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/CancelButton.js
  webpack/ForemanTasks/Components/common/ActionButtons/CancelButton.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/ResumeButton.js
  webpack/ForemanTasks/Components/common/ActionButtons/ResumeButton.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/__snapshots__/ActionButton.test.js.snap
  webpack/ForemanTasks/Components/common/ActionButtons/__snapshots__/CancelButton.test.js.snap
  webpack/ForemanTasks/Components/common/ActionButtons/__snapshots__/ResumeButton.test.js.snap
  webpack/ForemanTasks/Components/common/Cancel/Cancel.js
  webpack/ForemanTasks/Components/common/Cancel/Cancel.test.js
  webpack/ForemanTasks/Components/common/Cancel/__snapshots__/Cancel.test.js.snap
Labels: Needs testing

#472 Fixes #28215 - rename the second action column
  webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
Labels: Needs testing

#466 Add a duration column to the tasks table
  app/controllers/foreman_tasks/api/tasks_controller.rb
  webpack/ForemanTasks/Components/TasksTable/TaskTableFormmatters.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableHelpers.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableHelpers.test.js
Labels: Needs testing

#469 Fixes #27991 - Decreasing precision in Task Progress
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js
Labels: Needs testing

#475 Fixes #28244 - fix linting errors
  webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/index.js
  webpack/ForemanTasks/Components/TasksDashboard/index.js
  webpack/ForemanTasks/Components/TasksTable/index.js
Labels: Needs testing, Not yet reviewed

#463 Fixes #27855 - Add bulk cancel ui to tasks
  webpack/ForemanTasks/Components/TasksTable/Components/ActionConfirmation.js
  webpack/ForemanTasks/Components/TasksTable/Components/TableSelectionCell.js
  webpack/ForemanTasks/Components/TasksTable/Components/TableSelectionHeaderCell.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/ActionConfirmation.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/TableSelectionCell.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/TableSelectionHeaderCell.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/ActionConfirmation.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/TableSelectionCell.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/TableSelectionHeaderCell.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/TaskTableFormmatters.js
  webpack/ForemanTasks/Components/TasksTable/TasksTable.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableReducer.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableReducer.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableActions.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableReducer.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/actionCellFormatter.js
  webpack/ForemanTasks/Components/TasksTable/formatters/actionNameCellFormatter.js
  webpack/ForemanTasks/Components/TasksTable/formatters/dateCellFormmatter.js
  webpack/ForemanTasks/Components/TasksTable/formatters/durationCellFormmatter.js
  webpack/ForemanTasks/Components/TasksTable/formatters/index.js
  webpack/ForemanTasks/Components/TasksTable/formatters/selectionCellFormatter.js
  webpack/ForemanTasks/Components/TasksTable/formatters/selectionHeaderCellFormatter.js
  webpack/ForemanTasks/Components/TasksTable/index.js
Labels: Needs testing

#465 Fixes #27858 - Add bulk resume ui to tasks
  webpack/ForemanTasks/Components/TasksTable/Components/ActionSelectButton.js
  webpack/ForemanTasks/Components/TasksTable/Components/CancelResumeConfirm.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/ActionSelectButton.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/CancelResumeConfirm.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/ActionSelectButton.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/CancelResumeConfirm.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableReducer.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableReducer.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableActions.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableReducer.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/actionCellFormatter.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/actionNameCellFormatter.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/dateCellFormmatter.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/durationCellFormmatter.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/selectionCellFormatter.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/selectionHeaderCellFormatter.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/actionCellFormatter.test.js
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/actionNameCellFormatter.test.js
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/dateCellFormmatter.test.js
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/durationCellFormmatter.test.js
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/selectionCellFormatter.test.js
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/selectionHeaderCellFormatter.test.js
  webpack/ForemanTasks/Components/TasksTable/formatters/index.js
  webpack/ForemanTasks/Components/TasksTable/index.js
  webpack/__mocks__/foremanReact/components/common/table.js
Labels: Needs testing

#476 Fixes #28273 - Nullify user id on user destruction
  app/models/foreman_tasks/concerns/user_extensions.rb
  lib/foreman_tasks/engine.rb
  test/unit/task_test.rb
Labels: Needs testing

#479 Fixes #28306 - use label as fallback for tasks action name
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
Labels: Ready to merge

#478 Fixes #28302 - cleanup assets
  app/assets/javascripts/foreman_tasks/foreman_tasks.js
  app/assets/stylesheets/foreman_tasks/foreman_tasks.css
  app/assets/stylesheets/foreman_tasks/tasks.scss
  app/views/common/_trigger_form.html.erb
  app/views/foreman_tasks/tasks/show.html.erb
  lib/foreman_tasks/engine.rb
Labels: Ready to merge

#452 Fixes #27176 - adds subtask filter to tasks dashboard
  app/controllers/foreman_tasks/api/tasks_controller.rb
  app/controllers/foreman_tasks/tasks_controller.rb
  config/routes.rb
  lib/foreman_tasks/engine.rb
  webpack/ForemanTasks/Components/TasksDashboard/TasksDashboard.js
  webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardActions.js
  webpack/ForemanTasks/Components/TasksDashboard/__tests__/TaskDashboard.fixtures.js
  webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboardActions.test.js
  webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboardSelectors.test.js
  webpack/ForemanTasks/Components/TasksDashboard/__tests__/__snapshots__/TasksDashboardActions.test.js.snap
  webpack/ForemanTasks/Components/TasksDashboard/__tests__/__snapshots__/TasksDashboardSelectors.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/SubTasksPage.js
  webpack/ForemanTasks/Components/TasksTable/TasksTable.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableActions.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
Labels: Needs testing

#477 fixes #28276 - Improve cleanup task description
  lib/foreman_tasks/tasks/cleanup.rake
Labels: Needs testing
