Repository theforeman/foreman-tasks, pull requests merged in 2019-09, with the labels that each got.

#454 Fixes #27700 - update @theforeman/vendor to ^1.4.0
  package.json
Labels: Needs testing

#456 Refs #27700 - Bump required Foreman version to 1.24
  lib/foreman_tasks/engine.rb
Labels: Needs testing

#455 Fixes #27711 - Add IDs to tasks cards
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/PausedTasksCard/PausedTasksCard.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/PausedTasksCard/__snapshots__/PausedTasksCard.test.js.snap
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/RunningTasksCard/RunningTasksCard.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/RunningTasksCard/__snapshots__/RunningTasksCard.test.js.snap
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/ScheduledTasksCard/ScheduledTasksCard.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/ScheduledTasksCard/__snapshots__/ScheduledTasksCard.test.js.snap
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/StoppedTasksCard.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/__snapshots__/StoppedTasksCard.test.js.snap
Labels: Needs testing

#416 Fixes #26692 - allow passing partial updates to runner
  lib/foreman_tasks_core/otp_manager.rb
  lib/foreman_tasks_core/runner/base.rb
  lib/foreman_tasks_core/runner/dispatcher.rb
  test/unit/otp_manager_test.rb
Labels: Waiting on Dependencies

#457 Fixes #27792 - Make task dashboard honor set taxonomies
  app/controllers/foreman_tasks/tasks_controller.rb
  test/controllers/tasks_controller_test.rb
Labels: Needs testing

#458 Fixes #27803 - Add missing c3 dependency
  package.json
Labels: Needs testing, Not yet reviewed

#363 Fixes #25017 - Support all operators for search tasks by user
  app/models/foreman_tasks/task.rb
  app/models/foreman_tasks/task/search.rb
  test/unit/task_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#460 Fixes #27850 - Fix resource class errors in tests
  app/controllers/foreman_tasks/api/tasks_controller.rb
Labels: Needs testing, Not yet reviewed

#464 Fixes #27880 - change page removes active filters
  webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardHelper.js
Labels: Needs testing

#453 Fixes #27683 - tasks details should use the core date components
  webpack/ForemanTasks/Components/TaskDetails/Components/TaskHelper.js
  webpack/ForemanTasks/Components/TaskDetails/Components/TaskInfo.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/TaskHelper.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/TaskHelper.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/TaskInfo.test.js.snap
  webpack/__mocks__/foremanReact/common/helpers.js
  webpack/__mocks__/foremanReact/components/common/dates/RelativeDateTime.js
Labels: Needs testing
