Repository theforeman/foreman-tasks, pull requests merged in 2019-04, with the labels that each got.

#406 Fixes #22915 - optimized orphaned tasks query
  lib/foreman_tasks/cleaner.rb
Labels: Needs testing

#408 Refs #22602 - Add implicit casting from VARCHAR to UUID on postgres
  db/migrate/20190404132157_add_implicit_varchar_uuid_cast.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#407 Fixes #26527 - support for filtering by dashboard fields
  app/controllers/foreman_tasks/tasks_controller.rb
  app/models/foreman_tasks/task.rb
  app/services/foreman_tasks/dashboard_table_filter.rb
  test/foreman_tasks_test_helper.rb
  test/support/history_tasks_builder.rb
  test/unit/dashboard_table_filter_test.rb
  test/unit/summarizer_test.rb
Labels: Needs testing

#412 Accommodate the code for rubocop 0.64.0
  .rubocop.yml
  app/models/foreman_tasks/triggering.rb
Labels: Needs testing, Waiting on contributor

#410 Refs #26343 - change the look of stopped and scheduled cards
  webpack/ForemanTasks/Components/TasksDashboard/Components/ScheduledTasksCard/ScheduledTasksCard.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/ScheduledTasksCard/ScheduledTasksCard.scss
  webpack/ForemanTasks/Components/TasksDashboard/Components/ScheduledTasksCard/ScheduledTasksCard.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/ScheduledTasksCard/__snapshots__/ScheduledTasksCard.test.js.snap
  webpack/ForemanTasks/Components/TasksDashboard/Components/StoppedTasksCard/StoppedTasksCard.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/StoppedTasksCard/StoppedTasksCard.scss
  webpack/ForemanTasks/Components/TasksDashboard/Components/StoppedTasksCard/StoppedTasksCard.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/StoppedTasksCard/StoppedTasksCardHelper.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/StoppedTasksCard/__snapshots__/StoppedTasksCard.test.js.snap
Labels: Needs re-review, Needs testing

#411 Fixes #26560 - paused tasks notification and troubleshooting info
  .rubocop.yml
  app/controllers/foreman_tasks/api/tasks_controller.rb
  app/helpers/foreman_tasks/foreman_tasks_helper.rb
  app/lib/actions/base.rb
  app/models/foreman_tasks/task.rb
  app/models/setting/foreman_tasks.rb
  app/services/foreman_tasks/troubleshooting_help_generator.rb
  app/services/ui_notifications/tasks.rb
  app/services/ui_notifications/tasks/task_paused_admin.rb
  app/services/ui_notifications/tasks/task_paused_owner.rb
  app/views/foreman_tasks/tasks/_details.html.erb
  db/seeds.d/30-notification_blueprints.rb
  foreman-tasks.gemspec
  lib/foreman_tasks/test_helpers.rb
  test/foreman_tasks_test_helper.rb
  test/support/dummy_dynflow_action.rb
  test/unit/actions/action_with_sub_plans_test.rb
  test/unit/troubleshooting_help_generator_test.rb
  test/unit/ui_notifications_test.rb
Labels: Needs testing

#413 Fixes #26626 - log task state and result changes
  app/lib/actions/base.rb
  app/lib/actions/helpers/lifecycle_logging.rb
  test/unit/actions/action_with_sub_plans_test.rb
  test/unit/actions/bulk_action_test.rb
Labels: Needs testing, Not yet reviewed

#417 Fixes #26708 - sync npm version with packaging
  package.json
Labels: Needs testing

#418 Fix typo in the gemspec summary
  foreman-tasks.gemspec
Labels: Needs testing, Not yet reviewed, Waiting on contributor
