Repository theforeman/foreman-tasks, pull requests merged in 2020-01, with the labels that each got.

#488 Fixes #28614 - core API refactor breaks tasks pagination
  webpack/ForemanTasks/Components/TasksTable/TasksTableReducer.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableReducer.test.js
Labels: Needs testing

#483 Use @theforeman/stories
  .eslintrc
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  babel.config.js
  package.json
  webpack/ForemanTasks/Components/TaskDetails/TaskDetails.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/PausedTasksCard/PausedTasksCard.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/RunningTasksCard/RunningTasksCard.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/ScheduledTasksCard/ScheduledTasksCard.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/StoppedTasksCard.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/TasksDonutCard/TasksDonutCard.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/TasksDonutChart/TasksDonutChart.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/TasksCardsGrid.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksLabelsRow/TasksLabelsRow.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksTimeRow/Components/TimeDropDown/TimeDropDown.stories.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksTimeRow/Components/TimeDropDown/TimeDropDown.stories.mdx
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksTimeRow/TasksTimeRow.stories.js
  webpack/stories/index.js
  webpack/stories/index.scss
Labels: Needs testing

#493 Fixes #28634 - adjusts select for nulls ids
  app/controllers/foreman_tasks/api/tasks_controller.rb
  test/controllers/api/tasks_controller_test.rb
Labels: Needs testing

#495 Fixes #28670 - missing identity-obj-proxy package for tests
  package.json
Labels: Needs testing

#487 Fixes #28569 - consume jest from @theforeman
  package.json
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/Errors.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/Locks.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/Raw.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/RunningSteps.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/Task.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/TaskInfo.test.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/TaskDetails.test.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/TaskDetailsActions.test.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/TaskDetailsReducer.test.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/integration.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/PausedTasksCard/PausedTasksCard.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/RunningTasksCard/RunningTasksCard.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/ScheduledTasksCard/ScheduledTasksCard.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/StoppedTasksCard/StoppedTasksCard.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/TasksDonutCard/TasksDonutCard.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/TasksDonutChart/TasksDonutChart.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/TasksCardsGrid.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksLabelsRow/TasksLabelsRow.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksTimeRow/Components/TimeDropDown/TimeDropDown.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksTimeRow/TasksTimeRow.test.js
  webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboard.test.js
  webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboardActions.test.js
  webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboardReducer.test.js
  webpack/ForemanTasks/Components/TasksDashboard/__tests__/TasksDashboardSelectors.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/ActionConfirmation.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/ActionSelectButton.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/CancelResumeConfirm.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/TableSelectionCell.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/TableSelectionHeaderCell.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/SubTasksPage.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksIndexPage.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTablePage.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableReducer.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/CancelButton.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/ResumeButton.test.js
  webpack/ForemanTasks/ForemanTasks.test.js
  webpack/ForemanTasks/Routes/ForemanTasksRouter.test.js
  webpack/ForemanTasks/Routes/ForemanTasksRoutes.test.js
  webpack/ForemanTasks/Routes/ShowTask/__tests__/ShowTask.test.js
  webpack/test_setup.js
Labels: Needs re-review, Needs testing

#494 Fixes #28666 - adds support vendor v4
  package.json
Labels: Needs testing, Not yet reviewed

#491 Fixes #28319 - selectResults selector should be memorized
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
Labels: Needs testing, Not yet reviewed

#473 Fixes #28237 - Add confirmation modal for the tasks table
  webpack/ForemanTasks/Components/TasksTable/Components/ActionConfirmation.js
  webpack/ForemanTasks/Components/TasksTable/Components/CancelConfirm.js
  webpack/ForemanTasks/Components/TasksTable/Components/CancelResumeConfirm.js
  webpack/ForemanTasks/Components/TasksTable/Components/ConfirmationModals.js
  webpack/ForemanTasks/Components/TasksTable/Components/ResumeConfirm.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/ActionConfirmation.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/CancelConfirm.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/CancelResumeConfirm.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/ConfirmationModals.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/ResumeConfirm.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/ActionConfirmation.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/CancelConfirm.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/CancelResumeConfirm.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/ConfirmationModals.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/ResumeConfirm.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/TasksTable.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableReducer.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableReducer.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableReducer.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/index.js
  webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.js
  webpack/ForemanTasks/Components/common/ActionButtons/__snapshots__/ActionButton.test.js.snap
  webpack/__mocks__/foremanReact/components/ForemanModal/ForemanModalActions.js
  webpack/__mocks__/foremanReact/components/ForemanModal/ForemanModalHooks.js
  webpack/__mocks__/foremanReact/components/ForemanModal/index.js
Labels: Needs testing

#484 Fixes #28460 - adding eslint-plugin-foreman for styling
  .eslintrc
  package.json
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksCardsGrid/Components/TasksDonutChart/TasksDonutChart.test.js
  webpack/ForemanTasks/Components/TasksDashboard/Components/TasksTimeRow/TasksTimeRow.stories.js
  webpack/ForemanTasks/Components/TasksTable/TasksTable.js
Labels: Needs testing

#498 Fixes #28748 - task id fallback when there is no label
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
Labels: Needs testing

#482 Fixes #28416 - use bulk resume api in tasks table button
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableActions.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
Labels: Needs testing

#499 Fixes #28822 - task Search requires clicking twice on Search
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
Labels: Ready to merge

#497 Refs #28569 - clean up js deps
  package.json
Labels: Needs re-review, Needs testing

#489 Fixes #28095 - Make concurrency control work with batch triggering
  app/lib/actions/proxy_action.rb
  app/models/foreman_tasks/remote_task.rb
Labels: Needs testing, Waiting on contributor
