Repository theforeman/foreman-tasks, pull requests merged in 2020-03, with the labels that each got.

#515 Fixes #27951 - add dynflow requirement
  lib/foreman_tasks_core/ticker.rb
Labels: Needs testing

#518 Fixes #29286 - Update Rubocop to 0.80
  .rubocop.yml
  .rubocop_todo.yml
  app/helpers/foreman_tasks/foreman_tasks_helper.rb
Labels: Needs testing

#500 Fixes #20042 - add a clear button to recurring logics
  app/controllers/foreman_tasks/recurring_logics_controller.rb
  app/models/foreman_tasks/recurring_logic.rb
  app/views/foreman_tasks/recurring_logics/index.html.erb
  config/routes.rb
  lib/foreman_tasks/engine.rb
Labels: Needs testing

#513 Fixes #29030 - dynflow console button is no longer disabled
  app/views/foreman_tasks/api/tasks/details.json.rabl
  webpack/ForemanTasks/Components/TaskDetails/Components/Task.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/Task.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/index.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
Labels: Needs testing

#511 Fixes #29201 - Non-admin users are unable to view recurring logics
  app/controllers/foreman_tasks/recurring_logics_controller.rb
Labels: Needs testing, Waiting on contributor

#520 Fixes #29333 - enable and fix more cops
  .rubocop_todo.yml
  app/controllers/foreman_tasks/concerns/hosts_controller_extension.rb
  app/lib/actions/helpers/humanizer.rb
  app/models/foreman_tasks/concerns/action_triggering.rb
  app/models/foreman_tasks/task/dynflow_task.rb
  app/views/foreman_tasks/api/tasks/details.json.rabl
  foreman-tasks-core.gemspec
  foreman-tasks.gemspec
  lib/foreman_tasks/dynflow/console_authorizer.rb
  lib/foreman_tasks/engine.rb
  lib/foreman_tasks/test_extensions.rb
  locale/action_names.rb
  script/rails
  test/factories/task_factory.rb
  test/unit/actions/action_with_sub_plans_test.rb
Labels: Needs testing

#522 Fixes #29401 - add rubocop-minitest
  .rubocop.yml
  .rubocop_todo.yml
Labels: Needs testing, Not yet reviewed

#501 Fixes #28933 - add api to delete recurring logics
  app/controllers/foreman_tasks/api/recurring_logics_controller.rb
  config/routes.rb
  lib/foreman_tasks/engine.rb
Labels: Needs testing
