Repository theforeman/foreman-tasks, pull requests merged in 2020-05, with the labels that each got.

#519 Fixes #29088 - add select all to tasks table
  app/controllers/foreman_tasks/api/tasks_controller.rb
  app/services/ui_notifications/tasks/task_bulk_cancel.rb
  app/services/ui_notifications/tasks/task_bulk_resume.rb
  db/seeds.d/30-notification_blueprints.rb
  webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardConstants.js
  webpack/ForemanTasks/Components/TasksDashboard/TasksDashboardHelper.js
  webpack/ForemanTasks/Components/TasksTable/Components/SelectAllAlert.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/SelectAllAlert.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/__test__/__snapshots__/SelectAllAlert.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/TasksBulkActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTable.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActionHelpers.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableReducer.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksBulkActions.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTable.fixtures.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActionHelpers.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableReducer.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/SubTasksPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksBulkActions.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksIndexPage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableActions.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableReducer.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/selectionHeaderCellFormatter.test.js
  webpack/ForemanTasks/Components/TasksTable/formatters/selectionHeaderCellFormatter.js
  webpack/ForemanTasks/Components/TasksTable/index.js
Labels: Needs testing

#524 Fixes #29423 - Add setting for increasing polling intervals
  app/lib/foreman_tasks/concerns/polling_action_extensions.rb
  app/models/setting/foreman_tasks.rb
  lib/foreman_tasks/engine.rb
  test/lib/concerns/polling_action_extensions_test.rb
Labels: Needs testing, Waiting on contributor

#540 Fixes #29495 Filter trailing forward slash from task URL
  webpack/ForemanTasks/Components/TaskDetails/TasksDetailsHelper.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/TaskDetails.test.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/__tests__/integration.test.js
Labels: Needs testing

#536 Refs #29597 - refactor task actions buttons
  webpack/ForemanTasks/Components/TaskDetails/Components/Task.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/Task.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
  webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.js
  webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/CancelButton.js
  webpack/ForemanTasks/Components/common/ActionButtons/CancelButton.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/ResumeButton.js
  webpack/ForemanTasks/Components/common/ActionButtons/ResumeButton.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/__snapshots__/ActionButton.test.js.snap
  webpack/ForemanTasks/Components/common/ActionButtons/__snapshots__/CancelButton.test.js.snap
  webpack/ForemanTasks/Components/common/ActionButtons/__snapshots__/ResumeButton.test.js.snap
  webpack/__mocks__/foremanReact/components/common/ActionButtons/ActionButtons.js
Labels: Needs testing

#537 Refs #29597 - refactor task actions folders
  webpack/ForemanTasks/Components/TaskActions/TaskAction.test.js
  webpack/ForemanTasks/Components/TaskActions/TaskActionHelpers.js
  webpack/ForemanTasks/Components/TaskActions/TaskActionHelpers.test.js
  webpack/ForemanTasks/Components/TaskActions/TaskActionsConstants.js
  webpack/ForemanTasks/Components/TaskActions/__snapshots__/TaskAction.test.js.snap
  webpack/ForemanTasks/Components/TaskActions/index.js
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsActions.js
  webpack/ForemanTasks/Components/TaskDetails/index.js
  webpack/ForemanTasks/Components/TasksTable/TasksBulkActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableActions.test.js.snap
Labels: Needs testing

#545 Fixes #29594 - Fix wrong bookmark controller
  db/migrate/20200517215015_rename_bookmarks_controller.rb
  webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
Labels: Needs testing

#546 Refs #29423 - Enforce the polling multiplier to be >=1
  app/models/setting/foreman_tasks.rb
Labels: Needs testing

#542 i18n - pulling from tx
  locale/action_names.rb
  locale/en/foreman_tasks.po
  locale/foreman_tasks.pot
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#533 Fixes #29632 - unlock modals should use ForemanModal
  webpack/ForemanTasks/Components/TaskActions/TaskActionsConstants.js
  webpack/ForemanTasks/Components/TaskActions/index.js
  webpack/ForemanTasks/Components/TaskDetails/Components/Task.js
  webpack/ForemanTasks/Components/TaskDetails/Components/UnlockModals.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/Task.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/UnlockModals.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/UnlockModals.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsConstants.js
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsReducer.js
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/index.js
  webpack/ForemanTasks/Components/common/ClickConfirmation/ClickConfirmation.test.js
  webpack/ForemanTasks/Components/common/ClickConfirmation/__snapshots__/ClickConfirmation.test.js.snap
  webpack/ForemanTasks/Components/common/ClickConfirmation/index.js
  webpack/__mocks__/foremanReact/components/ForemanModal/ForemanModalHooks.js
  webpack/__mocks__/foremanReact/components/ForemanModal/index.js
Labels: Needs testing

#541 Fixes #29729 - add force unlock to tasks table rows
  webpack/ForemanTasks/Components/TaskActions/TaskActionHelpers.js
  webpack/ForemanTasks/Components/TaskActions/UnlockModals.js
  webpack/ForemanTasks/Components/TaskActions/__snapshots__/TaskAction.test.js.snap
  webpack/ForemanTasks/Components/TaskActions/__snapshots__/UnlockModals.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModal.js
  webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModalActions.js
  webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModalReducer.js
  webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/ConfirmModalSelectors.js
  webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/__test__/ConfirmModal.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/__test__/ConfirmModalActions.test.js
  webpack/ForemanTasks/Components/TasksTable/Components/ConfirmModal/__test__/__snapshots__/ConfirmModal.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/TasksTable.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSchema.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.js
  webpack/ForemanTasks/Components/common/ActionButtons/ActionButton.test.js
  webpack/ForemanTasks/Components/common/ActionButtons/__snapshots__/ActionButton.test.js.snap
Labels: Needs testing

#543 Fixes #29731 - Add bulk force unlock api for tasks
  app/controllers/foreman_tasks/api/tasks_controller.rb
  app/services/ui_notifications/tasks/task_bulk_stop.rb
  config/routes.rb
  db/seeds.d/30-notification_blueprints.rb
  lib/foreman_tasks/engine.rb
Labels: Needs testing

#490 Fixes #28776 - Adding Jail for task model
  app/models/foreman_tasks/task.rb
Labels: Needs testing
