Repository theforeman/foreman-tasks, pull requests merged in 2020-02, with the labels that each got.

#504 Fixes #29028 - RunHostsJob failed to update task status
  app/lib/actions/proxy_action.rb
Labels: Needs testing

#506 Fixes #29023 - Add title to tasks page
  app/views/foreman_tasks/tasks/show.html.erb
  webpack/ForemanTasks/Components/TasksTable/SubTasksPage.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
Labels: Needs testing, Not yet reviewed

#505 Fix search for multiple resource_ids
  app/models/foreman_tasks/task.rb
  app/models/foreman_tasks/task/search.rb
  test/factories/task_factory.rb
  test/unit/task_test.rb
Labels: Ready to merge

#507 Fixes #29136 - unable to cancel-resume task from table
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableActions.test.js
Labels: Ready to merge

#509 Fixes #29087 - Tasks should show Full name
  webpack/ForemanTasks/Components/TaskDetails/Components/TaskInfo.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/TaskInfo.test.js.snap
Labels: Ready to merge

#503 Fixes #29003 - Fix controller path for task search bookmarks
  webpack/ForemanTasks/Components/TasksTable/TasksTableConstants.js
Labels: Needs testing, Waiting on contributor

#508 Fixes #29045 - HTML tags visible on paused task page
  app/helpers/foreman_tasks/foreman_tasks_helper.rb
  app/services/foreman_tasks/troubleshooting_help_generator.rb
  package.json
  webpack/ForemanTasks/Components/TaskDetails/Components/TaskInfo.js
Labels: Needs re-review, Needs testing

#502 Fixes #28978 - Add description to plugin roles
  lib/foreman_tasks/engine.rb
Labels: Needs testing

#512 Fixes #29203 - Fix an edge case with excessive progress precision
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js
Labels: Needs testing
