Repository theforeman/foreman-tasks, pull requests merged in 2020-08, with the labels that each got.

#564 Fixes #30183 - use new UI API in tasks details
  webpack/ForemanTasks/Components/TaskDetails/Components/RunningSteps.js
  webpack/ForemanTasks/Components/TaskDetails/Components/Task.js
  webpack/ForemanTasks/Components/TaskDetails/Components/TaskButtons.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/RunningSteps.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/Task.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/TaskButtons.test.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Task.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/TaskDetails.js
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsActions.js
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsConstants.js
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsReducer.js
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/TaskDetails.fixtures.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/TaskDetails.test.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/TaskDetailsActions.test.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/TaskDetailsReducer.test.js
  webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetails.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetailsActions.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/TaskDetailsReducer.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/__tests__/__snapshots__/integration.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/__tests__/integration.test.js
  webpack/ForemanTasks/Components/TaskDetails/index.js
  webpack/ForemanTasks/Components/common/urlHelpers.js
  webpack/ForemanTasks/ForemanTasksReducers.js
  webpack/__mocks__/foremanReact/common/helpers.js
  webpack/__mocks__/foremanReact/redux/API.js
  webpack/__mocks__/foremanReact/redux/API/APISelectors.js
  webpack/__mocks__/foremanReact/redux/API/index.js
  webpack/__mocks__/foremanReact/redux/middlewares/IntervalMiddleware.js
Labels: Needs testing

#426 Fixes #27043 - Make rubocop work again
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/foreman_tasks/api/tasks_controller.rb
  app/controllers/foreman_tasks/concerns/parameters/triggering.rb
  app/helpers/foreman_tasks/foreman_tasks_helper.rb
  app/models/foreman_tasks/recurring_logic.rb
  app/models/foreman_tasks/task/dynflow_task.rb
  app/models/foreman_tasks/task/status_explicator.rb
  app/models/foreman_tasks/triggering.rb
  app/models/setting/foreman_tasks.rb
  db/migrate/20200517215015_rename_bookmarks_controller.rb
  db/seeds.d/30-notification_blueprints.rb
  db/seeds.d/61-foreman_tasks_bookmarks.rb
  lib/foreman_tasks/cleaner.rb
  lib/foreman_tasks/dynflow/configuration.rb
  lib/foreman_tasks/dynflow/persistence.rb
  lib/foreman_tasks/tasks/test.rake
  lib/foreman_tasks_core/runner/dispatcher.rb
  test/controllers/api/recurring_logics_controller_test.rb
  test/controllers/api/tasks_controller_test.rb
  test/controllers/tasks_controller_test.rb
  test/core/unit/runner_test.rb
  test/core/unit/task_launcher_test.rb
  test/helpers/foreman_tasks/foreman_tasks_helper_test.rb
  test/helpers/foreman_tasks/tasks_helper_test.rb
  test/lib/actions/middleware/keep_current_request_id_test.rb
  test/support/history_tasks_builder.rb
  test/tasks/generate_task_actions_test.rb
  test/unit/actions/action_with_sub_plans_test.rb
  test/unit/actions/bulk_action_test.rb
  test/unit/actions/proxy_action_test.rb
  test/unit/actions/recurring_action_test.rb
  test/unit/cleaner_test.rb
  test/unit/dashboard_table_filter_test.rb
  test/unit/otp_manager_test.rb
  test/unit/proxy_selector_test.rb
  test/unit/recurring_logic_test.rb
  test/unit/remote_task_test.rb
  test/unit/task_groups_test.rb
  test/unit/task_test.rb
  test/unit/triggering_test.rb
  test/unit/troubleshooting_help_generator_test.rb
  test/unit/ui_notifications_test.rb
Labels: Needs testing, Waiting on contributor

#577 Fixes #30621 - add toast to recurring logic state change
  app/controllers/foreman_tasks/recurring_logics_controller.rb
Labels: Needs testing

#576 Fixes #30623 - Add search to recurring logic table
  app/controllers/foreman_tasks/recurring_logics_controller.rb
  config/routes.rb
  lib/foreman_tasks/engine.rb
Labels: Needs testing

#575 Fixes #30622 - Add ID to recurring logics table
  app/views/foreman_tasks/recurring_logics/index.html.erb
Labels: Needs testing

#580 Update apt cache before performing package operation in CI
  .github/workflows/ruby_tests.yml
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#579 Fixes #30407 - removes unmaintained react-html-parser
  package.json
  webpack/ForemanTasks/Components/TaskDetails/Components/TaskInfo.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/TaskInfo.test.js.snap
Labels: Needs testing, Waiting on contributor
