Repository theforeman/foreman-tasks, pull requests merged in 2021-01, with the labels that each got.

#598 Fixes #31501 - Word Wrap for Long names in tasks table
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/actionNameCellFormatter.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/actionNameCellFormatter.js
Labels: Needs testing

#595 Fixes #31298 - Table pagination in react has extra space
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.scss
Labels: Needs testing

#222 Improved speed of rake export task
  lib/foreman_tasks/tasks/export_tasks.rake
Labels: Needs re-review, Needs testing, Waiting on contributor

#604 Refs #31501 - Word wrap for name in task details and table
  webpack/ForemanTasks/Components/TaskDetails/Components/TaskInfo.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/TaskInfo.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/TaskDetails.scss
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.scss
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/actionNameCellFormatter.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/actionNameCellFormatter.js
Labels: Needs testing

#600 Fixes #31534 - tasks search button should always reload data
  webpack/ForemanTasks/Components/TasksTable/TasksTableHelpers.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
Labels: Needs testing

#379 Fixes #25608 - Rework locking
  app/lib/actions/entry_action.rb
  app/lib/actions/helpers/lock.rb
  app/models/foreman_tasks/concerns/action_subject.rb
  app/models/foreman_tasks/link.rb
  app/models/foreman_tasks/lock.rb
  app/models/foreman_tasks/task.rb
  app/models/foreman_tasks/task/search.rb
  app/views/foreman_tasks/api/locks/show.json.rabl
  app/views/foreman_tasks/api/tasks/details.json.rabl
  app/views/foreman_tasks/tasks/_lock_card.html.erb
  db/migrate/20181206123910_create_foreman_tasks_links.foreman_tasks.rb
  db/migrate/20181206124952_migrate_non_exclusive_locks_to_links.foreman_tasks.rb
  db/migrate/20181206131436_drop_old_locks.foreman_tasks.rb
  db/migrate/20181206131627_make_locks_exclusive.foreman_tasks.rb
  lib/foreman_tasks/cleaner.rb
  test/controllers/tasks_controller_test.rb
  test/unit/actions/action_with_sub_plans_test.rb
  test/unit/cleaner_test.rb
  test/unit/lock_test.rb
  test/unit/locking_test.rb
  webpack/ForemanTasks/Components/TaskDetails/Components/Locks.js
  webpack/ForemanTasks/Components/TaskDetails/Components/__tests__/__snapshots__/Locks.test.js.snap
  webpack/ForemanTasks/Components/TaskDetails/TaskDetails.js
  webpack/ForemanTasks/Components/TaskDetails/TaskDetailsSelectors.js
  webpack/ForemanTasks/Components/TaskDetails/index.js
Labels: Needs testing

#592 Fixes #30161 - Make KeepCurrentUser cover entire transaction in finalize
  app/lib/actions/middleware/keep_current_user.rb
  lib/foreman_tasks/engine.rb
Labels: Needs testing, Waiting on contributor
