Repository theforeman/foreman-tasks, pull requests merged in 2021-06, with the labels that each got.

#628 Extract strings
  locale/action_names.rb
  locale/en/foreman_tasks.po
  locale/foreman_tasks.pot
  locale/fr/foreman_tasks.po
  locale/ja/foreman_tasks.po
  locale/zh_CN/foreman_tasks.po
Labels: Needs testing, Waiting on contributor

#635 Make tasks core only a compatibility layer to proxy plugin
  .github/workflows/ruby_tests.yml
  app/lib/actions/helpers/with_continuous_output.rb
  foreman-tasks-core.gemspec
  foreman-tasks.gemspec
  lib/foreman_tasks.rb
  lib/foreman_tasks/continuous_output.rb
  lib/foreman_tasks/engine.rb
  lib/foreman_tasks/tasks/test.rake
  lib/foreman_tasks_core.rb
  lib/foreman_tasks_core/batch_action.rb
  lib/foreman_tasks_core/batch_callback_action.rb
  lib/foreman_tasks_core/batch_runner_action.rb
  lib/foreman_tasks_core/otp_manager.rb
  lib/foreman_tasks_core/output_collector_action.rb
  lib/foreman_tasks_core/runner.rb
  lib/foreman_tasks_core/runner/action.rb
  lib/foreman_tasks_core/runner/base.rb
  lib/foreman_tasks_core/runner/command.rb
  lib/foreman_tasks_core/runner/command_runner.rb
  lib/foreman_tasks_core/runner/dispatcher.rb
  lib/foreman_tasks_core/runner/parent.rb
  lib/foreman_tasks_core/runner/update.rb
  lib/foreman_tasks_core/settings_loader.rb
  lib/foreman_tasks_core/shareable_action.rb
  lib/foreman_tasks_core/single_runner_batch_action.rb
  lib/foreman_tasks_core/task_launcher.rb
  lib/foreman_tasks_core/task_launcher/abstract.rb
  lib/foreman_tasks_core/task_launcher/batch.rb
  lib/foreman_tasks_core/task_launcher/group.rb
  lib/foreman_tasks_core/task_launcher/single.rb
  lib/foreman_tasks_core/ticker.rb
  test/core/unit/dispatcher_test.rb
  test/core/unit/runner_test.rb
  test/core/unit/task_launcher_test.rb
  test/foreman_tasks_core_test_helper.rb
  test/unit/otp_manager_test.rb
Labels: Needs testing, Waiting on contributor

#638 Fixes #32771 - adds taxonomy scope to API results
  app/controllers/concerns/foreman_tasks/find_tasks_common.rb
  app/controllers/foreman_tasks/api/tasks_controller.rb
  app/controllers/foreman_tasks/tasks_controller.rb
  test/controllers/api/tasks_controller_test.rb
Labels: Needs testing, Not yet reviewed

#514 Fixes #29223 - add latest_tasks by resource_ids
  app/models/foreman_tasks/task.rb
  test/unit/task_test.rb
Labels: Needs testing

#634 Fixes #32720 - Add graphql types
  app/graphql/types/recurring_logic.rb
  app/graphql/types/task.rb
  app/graphql/types/triggering.rb
  app/models/foreman_tasks/recurring_logic.rb
  app/models/foreman_tasks/task.rb
  app/models/foreman_tasks/triggering.rb
  lib/foreman_tasks/engine.rb
  test/graphql/queries/recurring_logic_test.rb
  test/graphql/queries/recurring_logics_query_test.rb
  test/graphql/queries/task_query_test.rb
  test/graphql/queries/tasks_query_test.rb
Labels: Needs testing, Not yet reviewed

#639 Fixes #32838 - Use AJ wrapper in case loading AJ fails
  app/models/foreman_tasks/task/dynflow_task.rb
Labels: Needs testing, Not yet reviewed
