Repository theforeman/foreman-tasks, pull requests merged in 2021-08, with the labels that each got.

#622 Fixes #32132 - Make tasks counts match when using dashboard
  app/controllers/foreman_tasks/api/tasks_controller.rb
  app/controllers/foreman_tasks/tasks_controller.rb
  app/lib/actions/middleware/watch_delegated_proxy_sub_tasks.rb
  app/services/foreman_tasks/dashboard_table_filter.rb
  test/unit/dashboard_table_filter_test.rb
  webpack/ForemanTasks/Components/TaskActions/TaskActionHelpers.js
  webpack/ForemanTasks/Components/TaskActions/TaskActionHelpers.test.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableActions.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableHelpers.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/TasksTableHelpers.test.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
Labels: Needs testing

#646 Fixes #31872 - Disable bulk actions when unauthorized
  webpack/ForemanTasks/Components/TasksTable/TasksTable.js
  webpack/ForemanTasks/Components/TasksTable/TasksTablePage.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableReducer.js
  webpack/ForemanTasks/Components/TasksTable/TasksTableSelectors.js
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTablePage.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/__tests__/__snapshots__/TasksTableReducer.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/__snapshots__/selectionHeaderCellFormatter.test.js.snap
  webpack/ForemanTasks/Components/TasksTable/formatters/__test__/selectionHeaderCellFormatter.test.js
  webpack/ForemanTasks/Components/TasksTable/formatters/selectionHeaderCellFormatter.js
  webpack/ForemanTasks/Components/TasksTable/index.js
Labels: Needs testing

#643 Fixes #33091 - Trigger recurring logic with a delay
  app/helpers/foreman_tasks/foreman_tasks_helper.rb
  app/models/foreman_tasks/triggering.rb
Labels: Needs testing, Not yet reviewed

#647 Fix typos in rake task interface scripts
  extra/foreman-tasks-cleanup.sh
  extra/foreman-tasks-export.sh
Labels: Needs testing, Not yet reviewed, Waiting on contributor
