Repository theforeman/foreman-tasks, pull requests merged in 2021-03, with the labels that each got.

#608 Fixes #31843 - Make sure logging context doesn't get wiped too early
  app/lib/actions/middleware/keep_current_request_id.rb
Labels: Ready to merge

#611 Fixes #31953 - ObservableAction jail doc
  app/lib/actions/observable_action.rb
Labels: Needs testing

#612 Refs #31773 - Fix pg syntax errors when searching by taxonomy
  app/models/foreman_tasks/task/search.rb
  test/unit/task_test.rb
Labels: Needs testing

#615 Add Ruby 2.7 support
  .github/workflows/ruby_tests.yml
Labels: Needs testing

#617 Fixes #32047 - Match proxy actions using task_id
  app/lib/actions/proxy_action.rb
Labels: Needs testing

#623 Refs #31457 - rename task output messages method
  app/models/foreman_tasks/task.rb
Labels: Needs testing

#621 Fixes #32094 - Fix leftovers after splitting locks
  app/controllers/foreman_tasks/api/tasks_controller.rb
  db/migrate/20180927120509_add_user_id.foreman_tasks.rb
Labels: Needs testing

#624 Refs #31953 - Show ObservableAction jail doc in section "all"
  app/lib/actions/observable_action.rb
Labels: Needs testing

#618 Fixes #32050 - Prevent BatchRunnerAction from collecting outputs
  lib/foreman_tasks_core/runner/parent.rb
Labels: Needs testing

#627 Fixes #32094 - Change locks to links in tests
  test/controllers/api/tasks_controller_test.rb
  test/controllers/tasks_controller_test.rb
Labels: Needs testing

#625 Fix test rake task used in CI
  .github/workflows/ruby_tests.yml
  test/core/unit/runner_test.rb
  test/factories/task_factory.rb
  test/unit/actions/proxy_action_test.rb
  test/unit/task_test.rb
  test/unit/triggering_test.rb
Labels: Needs testing, Waiting on contributor
