Repository theforeman/foreman-tasks, pull requests merged in 2022-03, with the labels that each got.

#670 Fixes #34108 - Sort generated tasks by date
  lib/foreman_tasks/tasks/export_tasks.rake
Labels: Needs testing

#671 Fixes #34412 - Add additional error logging
  app/lib/actions/trigger_proxy_batch.rb
  app/models/foreman_tasks/remote_task.rb
Labels: Needs testing

#668 Fixes #34343 - Unlock tasks on {force_,}unlock
  app/controllers/foreman_tasks/tasks_controller.rb
Labels: Needs testing, Not yet reviewed

#674 i18n - pulling from tx
  locale/action_names.rb
  locale/en/foreman_tasks.po
  locale/foreman_tasks.pot
  locale/fr/foreman_tasks.po
  locale/ja/foreman_tasks.po
  locale/zh_CN/foreman_tasks.po
Labels: Needs testing, Not yet reviewed, Waiting on contributor
